config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'


  resources :users, only: [:index, :new, :create]
  resources :categories, only: [:index, :show]
  resources :orders, only: [:show, :new, :create]
  resources :items, only: [:show, :index]
  # resources :carts, only: [:create, :update]

  post '/cart', to: 'cart_items#create'
  get '/cart', to: 'cart_items#index'
  put '/cart', to: 'cart_items#update'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/profile', to: 'users#show'

  get '/search', to: 'search#items'

  namespace :admin do
    put 'items/:id', to: 'items#update_status', :as => 'item_status'
    resources :users, only: [:show, :edit, :update]
    resources :categories, only: [:new, :create, :index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :edit, :update]
    resources :items, only: [:index, :show, :edit, :new, :create, :update]
    resources :category_items, only: [:new, :create]
    get '/category_items/new_category_to_item/:item_id', to: 'category_items#new_category_to_item', :as => 'new_category_to_item'
  end

  get '*unmatched_route', to: 'application#not_found'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :category_items
  has_many :items, through: :category_items
  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
before_action(:set_category, only: [:show, :edit, :update])

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def show
  end

  def edit
  end

  def create
    category = Category.new(category_params)
    if category.save
      redirect_to admin_categories_path
    else
      flash[:danger] = "oops that didn't persist to the database...as they say in the industry"
      redirect_to new_admin_category_path
    end
  end

  def update
    @category.update(category_params)
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find_by(id: params[:id])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find_by(id: params[:id])
  end
end

app/views/admin/categories/edit.html.erb
<h1>update <%= @category.name %> menu name</h1><br>

<div class="form-horizontal">
<%= form_for([:admin, @category]) do |f| %>
  <div class="field form-group">
    <%= f.label :name, "menu", class: 'col-sm-2 control-label' %>
    <div class="col-sm-3">
      <%= f.text_field :name, placeholder: @category.name, class: 'form-control' %>
    </div>
  </div>

  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "change", class: "btn btn-default" %>
    </div>
  </div>
<% end %>
</div>

<h4><%= link_to "menus", admin_categories_path %></h4>

app/views/admin/categories/index.html.erb
<h1>menus</h1>


<% @categories.each do |category| %>
  <div class="col-sm-4" style="text-align: center;">
    <h3><%= link_to category.name, admin_category_path(category) %></h3>
    <h4><%= link_to "edit", edit_admin_category_path(category) %></h4>
  </div>
<% end %>

<div class="col-sm-12">
<h4><%= link_to "add a menu", new_admin_category_path %></h4>

<h6><%= link_to "admin page", admin_user_path(current_user) %></h6>
</div>

app/views/admin/categories/new.html.erb
<div class="form-horizontal">
<%= form_for([:admin, @category]) do |f| %>
  <div class="field form-group">
    <%= f.label :name, "menu name", class: 'col-sm-2 control-label' %>
    <div class="col-sm-3">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "add menu", class: "btn btn-default" %>
    </div>
  </div>
<% end %>
</div>

app/views/admin/categories/show.html.erb
<h1><%= @category.name %></h1>
<ul>
  <% @category.items.each do |item| %>
    <li><%= item.title%></li>
  <% end %>

  <%= link_to "add item to this menu", new_admin_category_item_path(category_id: @category.id) %>
</ul>