config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'


  resources :users, only: [:index, :new, :create]
  resources :categories, only: [:index, :show]
  resources :orders, only: [:show, :new, :create]
  resources :items, only: [:show, :index]
  # resources :carts, only: [:create, :update]

  post '/cart', to: 'cart_items#create'
  get '/cart', to: 'cart_items#index'
  put '/cart', to: 'cart_items#update'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/profile', to: 'users#show'

  get '/search', to: 'search#items'

  namespace :admin do
    put 'items/:id', to: 'items#update_status', :as => 'item_status'
    resources :users, only: [:show, :edit, :update]
    resources :categories, only: [:new, :create, :index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :edit, :update]
    resources :items, only: [:index, :show, :edit, :new, :create, :update]
    resources :category_items, only: [:new, :create]
    get '/category_items/new_category_to_item/:item_id', to: 'category_items#new_category_to_item', :as => 'new_category_to_item'
  end

  get '*unmatched_route', to: 'application#not_found'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :category_items
  has_many :items, through: :category_items
  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
before_action(:set_category, only: [:show, :edit, :update])

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def show
  end

  def edit
  end

  def create
    category = Category.new(category_params)
    if category.save
      redirect_to admin_categories_path
    else
      flash[:danger] = "oops that didn't persist to the database...as they say in the industry"
      redirect_to new_admin_category_path
    end
  end

  def update
    @category.update(category_params)
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find_by(id: params[:id])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find_by(id: params[:id])
  end
end

app/views/categories/index.html.erb
<h1>menus</h1>

<% @categories.each do |category| %>
  <div class="col-lg-4 col-sm-4 center-in-column">
    <h3><%= link_to image_tag("#{category.name.split.first}.jpg"), category, id: "menulink" %></h3>
  </div>

<% end %>

<div class="col-lg-4 col-sm-4 center-in-column">
  <h3><%= link_to image_tag("all.jpg"), items_path %></h3>
</div>

app/views/categories/show.html.erb
<h1 id="menu-title"><%= @category.name %></h1>
<h3><%= link_to "menus", categories_path %><h3>
<!-- put the link to menus in the nav bar -->

<div class="row text-center">
  <% @category.items.active.each do |item| %>
    <div class="col-lg-6 col-sm-6">
      <div class="thumbnail">
        <%= link_to image_tag(item.image.url, alt: item.title, style: "height: 325px;"), item %>
      </div>
        <div class="caption">
          <h3><%= item.title %><h3>
          <%= button_to cart_path(item_id: item.id), class: 'btn btn-default' do %>
            <i class="glyphicon glyphicon-plus"></i> add to cart
            <% end %>
          </div><br>
      </div>
      <% end %>
</div>