config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'


  resources :users, only: [:index, :new, :create]
  resources :categories, only: [:index, :show]
  resources :orders, only: [:show, :new, :create]
  resources :items, only: [:show, :index]
  # resources :carts, only: [:create, :update]

  post '/cart', to: 'cart_items#create'
  get '/cart', to: 'cart_items#index'
  put '/cart', to: 'cart_items#update'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/profile', to: 'users#show'

  get '/search', to: 'search#items'

  namespace :admin do
    put 'items/:id', to: 'items#update_status', :as => 'item_status'
    resources :users, only: [:show, :edit, :update]
    resources :categories, only: [:new, :create, :index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :edit, :update]
    resources :items, only: [:index, :show, :edit, :new, :create, :update]
    resources :category_items, only: [:new, :create]
    get '/category_items/new_category_to_item/:item_id', to: 'category_items#new_category_to_item', :as => 'new_category_to_item'
  end

  get '*unmatched_route', to: 'application#not_found'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email, presence: true, uniqueness: true, confirmation: true
  validates :display_name, length: { in: 2..32 }, allow_blank: true
  validates_format_of :email, :with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/

  has_many :orders

  enum role: %w(default admin)

  def name
    self.display_name == "" ? self.full_name : self.display_name
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def show
    @categories = Category.all
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    if @user.update(user_params)
      flash[:success] = "you have updated your profile"
      redirect_to admin_user_path(@user)
    else
      flash.now[:danger] = @user.errors.full_messages.join(", ")
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:full_name, :display_name, :email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def show
    render file:"public/404" unless current_user
    @user = current_user
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to profile_path
    else
      flash[:danger] = @user.errors.full_messages.join(", ")
      redirect_to new_user_path
    end
  end

  private

  def user_params
    params.require(:user).permit( :email,
                                  :email_confirmation,
                                  :full_name,
                                  :display_name,
                                  :password,
                                  :password_confirmation)
  end
end

app/views/admin/users/edit.html.erb
<div class="form-horizontal">
  <%= form_for([:admin, @user]) do |f| %>
    <div class="field form-group">
      <%= f.label :full_name,"full name", class: 'col-sm-2 control-label' %>
    <div class="col-sm-3">
      <%= f.text_field :full_name, :value => @user.full_name, class: 'form-control' %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :display_name,"display name", class: 'col-sm-2 control-label' %>
  <div class="col-sm-3">
    <%= f.text_field :display_name,:value => @user.display_name, class: 'form-control' %>
  </div>
  </div>

  <div class="field form-group">
    <%= f.label :email,"email", class: 'col-sm-2 control-label' %>
  <div class="col-sm-3">
    <%= f.text_field :email,:value => @user.email, class: 'form-control' %>
  </div>
  </div>

    <div class="actions form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "update profile", class: "btn btn-default"%>
      </div>
    </div>
    <% end %>
</div>

app/views/admin/users/show.html.erb
<h1>admin | <%= current_user.name %></h1>

<div class="col-sm-3", style="text-align: center;">
  <h3><%= link_to "menus", admin_categories_path %></h3>
  <h6>add or edit a menu</h6>
</div>

<div class="col-sm-3", style="text-align: center;">
  <h3><%= link_to "items", admin_items_path %></h3>
  <h6>add or edit an item</h6>
</div>

<div class="col-sm-3", style="text-align: center;">
  <h3><%= link_to "orders", admin_orders_path %></h3>
  <h6>view or edit orders</h6>
</div>

<div class="col-sm-3", style="text-align: center;">
  <h3><%= link_to "edit profile", edit_admin_user_path(current_user) %></h3>
  <h6>edit your profile</h6>
</div>