config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'


  resources :users, only: [:index, :new, :create]
  resources :categories, only: [:index, :show]
  resources :orders, only: [:show, :new, :create]
  resources :items, only: [:show, :index]
  # resources :carts, only: [:create, :update]

  post '/cart', to: 'cart_items#create'
  get '/cart', to: 'cart_items#index'
  put '/cart', to: 'cart_items#update'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/profile', to: 'users#show'

  get '/search', to: 'search#items'

  namespace :admin do
    put 'items/:id', to: 'items#update_status', :as => 'item_status'
    resources :users, only: [:show, :edit, :update]
    resources :categories, only: [:new, :create, :index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :edit, :update]
    resources :items, only: [:index, :show, :edit, :new, :create, :update]
    resources :category_items, only: [:new, :create]
    get '/category_items/new_category_to_item/:item_id', to: 'category_items#new_category_to_item', :as => 'new_category_to_item'
  end

  get '*unmatched_route', to: 'application#not_found'
end

app/views/layouts/_nav.html.erb
<nav class="navbar" role="navigation">

    <div class="navbar-header">
      <a class="navbar-brand special-bigger" href="/">Farm to Table</a>
      <div class="form-inline">
      <%= form_tag search_path, :method => 'get' do %>
        <%= text_field_tag :search, params[:search], class: 'form-control' %>
        <%= submit_tag "search", class: "btn btn-default", :name => nil %>
      <% end %>
    </div>
  </div>

<div>
  <% if current_user %>
  <h1>  <%= link_to "logout", logout_path, method: :delete, class: 'btn btn-hover navbar-btn bigger' %></h1>
  <% if current_user.admin? %>
    <%= link_to admin_user_path(current_user), class: 'btn btn-default navbar-btn' do %>
      <i class="glyphicon glyphicon-user"></i>
    <% end %>
  <% else %>
    <%= link_to profile_path, class: 'btn btn-hover navbar-btn' do %>
      <i class="glyphicon glyphicon-user"></i>
      <% end %>

  <% end %>
  <% else %>
    <%= link_to "login", login_path, class: 'btn btn-hover navbar-btn bigger' %>
  <% end %>
    <%= link_to cart_path, id: 'cart', class: 'btn btn-hover navbar-btn' do %>
      <i class="glyphicon glyphicon-shopping-cart"></i>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FarmToTable - lettuce turnip the beet</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href='//fonts.googleapis.com/css?family=Oswald:400,700,300' rel='stylesheet' type='text/css'>
  <link href='//fonts.googleapis.com/css?family=Merriweather:400italic,400,300italic,300' rel='stylesheet' type='text/css'>
  <link href='//fonts.googleapis.com/css?family=Lobster+Two:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='//fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
</head>


<body>

<div class="container-fluid center-page">

<%= render partial: 'layouts/nav' %>

<% flash.each do |name, message| %>
  <div class="alert alert-<%= name %>" style="text-align: center;"><h5><%= message %></h5></div>
<% end %>


<%= yield %>


</div>
</body>

</html>